version: '3.9'

services:
  postgres:
    image: 'postgres:14.2'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "dbvehicle"
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"
  
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "9090:8081"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: e296cd9f
    