micronaut:
  application:
    name: reportService
  server:
    port: 8082
#netty:
#  default:
#    allocator:
#      max-order: 3
mongodb:
  url: 'mongodb://root:e296cd9f@ms-mongo:27017/admin'
kafka:
  bootstrap:
    servers: kafka-server:9092
consul:
  client:
    registration:
      enabled: true
    defaultZone: "ms-consul:8500"